export type ResumeVariant = {
  name: string;
  html: string;
};

const sharedStyles = `
  @import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap');
  *{box-sizing:border-box}body{margin:0;color:#111;font-family:Inter,ui-sans-serif,system-ui,sans-serif;font-size:14px;line-height:1.55}a{color:inherit;text-underline-offset:3px}h1,h2,h3,p{margin:0}ul{margin:0;padding-left:18px}li+li{margin-top:4px}.serif{font-family:Canela,Georgia,serif}.muted{color:#6b7280}.caps{text-transform:uppercase;letter-spacing:.13em;font-size:10px;font-weight:700}.resume{max-width:48rem;margin:0 auto}.contact{display:flex;flex-wrap:wrap;gap:6px 16px}.contact a{text-decoration:none}.contact a:hover{text-decoration:underline}@media(max-width:640px){body{font-size:13px}.contact{gap:4px 12px}}
`;

const editorial = `
<style>${sharedStyles}
  .resume{padding:10px 4px 40px}.hero{padding:24px 0 28px;border-bottom:1px solid rgba(0,0,0,.16)}.hero h1{font-size:clamp(42px,9vw,72px);line-height:.92;letter-spacing:-.045em;font-weight:400}.hero-row{display:flex;justify-content:space-between;align-items:flex-end;gap:24px;margin-top:20px}.hero p{max-width:480px;font-size:15px}.section{display:grid;grid-template-columns:120px 1fr;gap:28px;padding:28px 0;border-bottom:1px solid rgba(0,0,0,.12)}.section:last-child{border-bottom:0}.item+.item{margin-top:24px}.item-head{display:flex;justify-content:space-between;gap:20px;align-items:baseline}.item h3{font-size:16px}.date{white-space:nowrap;font-size:12px;color:#6b7280}.summary{font-family:Canela,Georgia,serif;font-size:22px;line-height:1.35}.project-grid{display:grid;grid-template-columns:1fr 1fr;gap:18px 28px}.project h3{font-size:14px;margin-bottom:4px}.skills{display:flex;flex-wrap:wrap;gap:8px}.skills span{border:1px solid rgba(0,0,0,.15);border-radius:999px;padding:4px 9px;font-size:12px}@media(max-width:640px){.hero-row,.item-head{align-items:flex-start;flex-direction:column;gap:8px}.section{grid-template-columns:1fr;gap:14px}.project-grid{grid-template-columns:1fr}.hero h1{font-size:48px}}
</style>
<main class="resume">
  <header class="hero">
    <p class="caps muted">Design engineer · AI builder · ultrarunner</p>
    <h1 class="serif">Tarun<br>Tomar.</h1>
    <div class="hero-row">
      <p>Design Engineer at Adobe building systems used across Firefly, Illustrator Web, and Adobe.com. I also build on-device AI products and experiments that ship.</p>
      <div class="contact muted"><a href="mailto:tomartarun2001@gmail.com">email</a><a href="https://www.tarat.space">tarat.space</a><a href="https://github.com/TarunTomar122">github</a><a href="https://x.com/tarat_211">@tarat_211</a></div>
    </div>
  </header>
  <section class="section"><h2 class="caps muted">Experience</h2><div>
    <article class="item"><div class="item-head"><h3>Adobe · Design Engineer (SDE II)</h3><span class="date">Jun 2023 — Present</span></div><ul><li>Led the architectural migration of Spectrum Web Components to Spectrum 2.0, impacting Firefly, Illustrator Web, Adobe.com, and thousands of engineers.</li><li>Built App Frame from scratch for cross-platform rendering, WCAG accessibility, and design consistency.</li><li>Built internal tooling to track component adoption across Adobe; promoted to SDE II in January 2025.</li></ul></article>
    <article class="item"><div class="item-head"><h3>Adobe · Emerging Tech Intern</h3><span class="date">May — Jul 2022</span></div><p>Built a multimodal GenAI assistant for Adobe Express covering template matching, context-aware canvas editing, and asset generation.</p></article>
  </div></section>
  <section class="section"><h2 class="caps muted">Selected work</h2><div class="project-grid">
    <article class="project"><h3><a href="https://www.tarat.space/projects/lumi">Lumi ↗</a></h3><p>350M-parameter on-device Android LLM with sub-100ms inference, 400+ users, offline-first tasks, and paid conversions.</p></article>
    <article class="project"><h3><a href="https://www.tarat.space/projects/deepseek-nanochat-1">Vision NanoChat ↗</a></h3><p>BLIP-2 plus a custom 1.5M-parameter projection layer for 64× visual-token compression.</p></article>
    <article class="project"><h3><a href="https://yourtrace.online">YourTrace ↗</a></h3><p>Daily AI/tech briefing with 200+ mobile downloads and a Product Hunt #7 launch.</p></article>
    <article class="project"><h3><a href="https://stocksbrew.online">StocksBrew ↗</a></h3><p>AI-curated stock briefings delivered before market open; a live, revenue-generating product.</p></article>
    <article class="project"><h3><a href="https://www.tarat.space/projects/garden-rag">Garden RAG ↗</a></h3><p>Client-side semantic search over projects, writing, and experience.</p></article>
    <article class="project"><h3><a href="https://www.tarat.space/projects/ml-implementation">ML from Scratch ↗</a></h3><p>Open-source Python ML library built with 30+ contributors worldwide.</p></article>
  </div></section>
  <section class="section"><h2 class="caps muted">Toolbox</h2><div class="skills"><span>TypeScript</span><span>React / Next.js</span><span>Web Components</span><span>Design systems</span><span>Accessibility</span><span>Python</span><span>PyTorch</span><span>Vision-language models</span><span>LoRA / PEFT</span><span>On-device inference</span><span>RAG</span></div></section>
  <section class="section"><h2 class="caps muted">Education</h2><div><article class="item"><div class="item-head"><h3>MSc Artificial Intelligence · University of Edinburgh</h3><span class="date">Sep 2026 — Sep 2027</span></div><p class="muted">Incoming</p></article><article class="item"><div class="item-head"><h3>B.Tech Computer Science · IIT Jodhpur</h3><span class="date">Graduated May 2023</span></div><p class="muted">CGPA 8.0 / 10</p></article></div></section>
</main>`;

const sidebar = `
<style>${sharedStyles}
  .resume{display:grid;grid-template-columns:210px 1fr;min-height:900px;border:1px solid rgba(0,0,0,.12);border-radius:12px;overflow:hidden}.rail{background:#f5edd8;padding:34px 24px}.rail h1{font-size:42px;line-height:.95;font-weight:400;letter-spacing:-.04em;margin-bottom:18px}.rail section{margin-top:32px}.rail h2,.main h2{margin-bottom:12px}.rail .contact{display:grid;gap:7px}.rail ul{list-style:none;padding:0}.rail li+li{margin-top:6px}.main{padding:34px 32px}.intro{font-family:Canela,Georgia,serif;font-size:25px;line-height:1.35;padding-bottom:28px;border-bottom:1px solid rgba(0,0,0,.14)}.main section{padding:26px 0;border-bottom:1px solid rgba(0,0,0,.12)}.main section:last-child{border:0}.role+.role{margin-top:24px}.role-head{display:grid;grid-template-columns:1fr auto;gap:16px;margin-bottom:8px}.role h3{font-size:16px}.date{font-size:11px;color:#6b7280}.projects{display:grid;gap:10px}.project{display:grid;grid-template-columns:140px 1fr;gap:14px;padding:12px 0;border-top:1px dashed rgba(0,0,0,.16)}.project:first-child{border-top:0;padding-top:0}.project h3{font-size:13px}.edu+.edu{margin-top:14px}@media(max-width:680px){.resume{grid-template-columns:1fr}.rail{padding:26px 20px}.rail h1{font-size:46px}.rail-grid{display:grid;grid-template-columns:1fr 1fr;gap:0 24px}.main{padding:28px 20px}.project{grid-template-columns:1fr;gap:4px}}
</style>
<main class="resume">
  <aside class="rail"><h1 class="serif">Tarun<br>Tomar</h1><p class="muted">Design Engineer at Adobe.<br>AI builder. Ultramarathon runner.</p><div class="rail-grid">
    <section><h2 class="caps">Contact</h2><div class="contact muted"><a href="mailto:tomartarun2001@gmail.com">tomartarun2001@gmail.com</a><a href="https://www.tarat.space">tarat.space</a><a href="https://github.com/TarunTomar122">GitHub</a><a href="https://x.com/tarat_211">X / Twitter</a><span>India → Edinburgh, Sep 2026</span></div></section>
    <section><h2 class="caps">Core stack</h2><ul class="muted"><li>React & Next.js</li><li>TypeScript</li><li>Web Components</li><li>Design systems</li><li>Accessibility</li><li>Python & PyTorch</li><li>Vision-language models</li><li>On-device inference</li></ul></section>
    <section><h2 class="caps">Beyond work</h2><p class="muted">4.3K YouTube subscribers. Finished a 51km ultramarathon in 6:47.</p></section>
  </div></aside>
  <div class="main"><p class="intro">I build design infrastructure for thousands of engineers, then spend the rest of my time shipping small AI systems with real users.</p>
    <section><h2 class="caps muted">Experience</h2><article class="role"><div class="role-head"><h3>Design Engineer (SDE II) · Adobe</h3><span class="date">JUN 2023 — NOW</span></div><ul><li>Led Spectrum Web Components’ migration to Spectrum 2.0 across Firefly, Illustrator Web, and Adobe.com.</li><li>Created App Frame with cross-platform rendering, WCAG accessibility, and consistent design behavior.</li><li>Built adoption-tracking tooling for Adobe’s component ecosystem; promoted January 2025.</li></ul></article><article class="role"><div class="role-head"><h3>Emerging Tech Intern · Adobe</h3><span class="date">MAY — JUL 2022</span></div><p>Built a multimodal GenAI assistant for Adobe Express with template matching, canvas editing, and asset generation.</p></article></section>
    <section><h2 class="caps muted">Proof of work</h2><div class="projects">
      <article class="project"><h3><a href="https://www.tarat.space/projects/lumi">Lumi ↗</a></h3><p>On-device 350M LLM todo app: sub-100ms inference, offline-first, 400+ Play Store users.</p></article>
      <article class="project"><h3><a href="https://www.tarat.space/projects/deepseek-nanochat-1">Vision NanoChat ↗</a></h3><p>64× visual-token compression through BLIP-2 and a custom projection layer.</p></article>
      <article class="project"><h3><a href="https://yourtrace.online">YourTrace ↗</a></h3><p>AI/tech briefing: Product Hunt #7, 200+ mobile downloads, and recurring revenue.</p></article>
      <article class="project"><h3><a href="https://stocksbrew.online">StocksBrew ↗</a></h3><p>Daily AI-curated stock briefings delivered before market open.</p></article>
      <article class="project"><h3><a href="https://www.tarat.space/tarat-ai">Garden RAG ↗</a></h3><p>Browser-based RAG across my garden’s writing, projects, and experience.</p></article>
    </div></section>
    <section><h2 class="caps muted">Education</h2><div class="edu"><strong>MSc Artificial Intelligence · University of Edinburgh</strong><p class="muted">Incoming, Sep 2026 — Sep 2027</p></div><div class="edu"><strong>B.Tech Computer Science · IIT Jodhpur</strong><p class="muted">May 2023 · CGPA 8.0 / 10</p></div></section>
  </div>
</main>`;

const swiss = `
<style>${sharedStyles}
  body{font-size:13px}.resume{padding:8px 0 40px}.mast{display:grid;grid-template-columns:1.35fr .65fr;gap:30px;padding:20px 0 26px;border-top:5px solid #111;border-bottom:1px solid #111}.mast h1{font-family:Inter,sans-serif;font-size:clamp(52px,10vw,82px);line-height:.82;letter-spacing:-.075em}.mast-right{align-self:end}.mast-right p{max-width:250px}.contact{margin-top:14px;font-size:11px}.section{display:grid;grid-template-columns:64px 1fr;padding:25px 0;border-bottom:1px solid #111}.no{font-size:11px;font-weight:700}.section h2{font-size:11px;text-transform:uppercase;letter-spacing:.14em;margin-bottom:16px}.jobs{display:grid;grid-template-columns:1fr 1fr;gap:22px}.job{border-top:3px solid #111;padding-top:10px}.job h3{font-size:15px;margin-bottom:2px}.job .date{font-size:10px;letter-spacing:.08em;text-transform:uppercase;color:#6b7280;margin-bottom:12px}.project-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:1px;background:#111;border:1px solid #111}.project{background:#fdf5e2;padding:15px;min-height:142px}.project h3{font-size:14px;margin-bottom:8px}.project p{font-size:12px}.skill-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:12px}.skill-grid h3{font-size:11px;text-transform:uppercase;margin-bottom:5px}.edu{display:flex;justify-content:space-between;gap:20px}.edu+.edu{margin-top:12px}@media(max-width:640px){.mast{grid-template-columns:1fr}.mast h1{font-size:58px}.mast-right{align-self:auto}.section{grid-template-columns:38px 1fr}.jobs,.project-grid{grid-template-columns:1fr}.skill-grid{grid-template-columns:1fr 1fr}.project{min-height:0}.edu{display:block}}
</style>
<main class="resume">
  <header class="mast"><h1>TARUN<br>TOMAR</h1><div class="mast-right"><p>Design engineer building accessible systems at Adobe and compact AI products everywhere else.</p><div class="contact muted"><a href="mailto:tomartarun2001@gmail.com">Email</a><a href="https://www.tarat.space">Web</a><a href="https://github.com/TarunTomar122">GitHub</a><a href="https://x.com/tarat_211">X</a></div></div></header>
  <section class="section"><span class="no">01</span><div><h2>Experience</h2><div class="jobs"><article class="job"><h3>Adobe · Design Engineer (SDE II)</h3><p class="date">June 2023 — Present</p><ul><li>Led Spectrum Web Components’ Spectrum 2.0 migration for products including Firefly, Illustrator Web, and Adobe.com.</li><li>Built the accessible, cross-platform App Frame component from scratch.</li><li>Created component-adoption tooling; promoted January 2025.</li></ul></article><article class="job"><h3>Adobe · Emerging Tech Intern</h3><p class="date">May — July 2022</p><p>Built a multimodal GenAI assistant for Adobe Express spanning template matching, context-aware editing, and asset generation.</p></article></div></div></section>
  <section class="section"><span class="no">02</span><div><h2>Selected systems & products</h2><div class="project-grid">
    <article class="project"><h3><a href="https://www.tarat.space/projects/lumi">Lumi ↗</a></h3><p>350M on-device LLM. &lt;100ms inference. 400+ Android users. Offline-first.</p></article><article class="project"><h3><a href="https://www.tarat.space/projects/deepseek-nanochat-1">Vision NanoChat ↗</a></h3><p>Custom 1.5M projection layer for 64× visual-token compression.</p></article><article class="project"><h3><a href="https://yourtrace.online">YourTrace ↗</a></h3><p>Daily AI briefing. Product Hunt #7. 200+ app downloads.</p></article><article class="project"><h3><a href="https://stocksbrew.online">StocksBrew ↗</a></h3><p>Automated pre-market stock briefings with recurring revenue.</p></article><article class="project"><h3><a href="https://www.tarat.space/projects/garden-rag">Garden RAG ↗</a></h3><p>Client-side semantic search and grounded garden Q&A.</p></article><article class="project"><h3><a href="https://www.tarat.space/projects/ml-implementation">ML/DL Library ↗</a></h3><p>Algorithms from scratch in Python; 30+ global contributors.</p></article>
  </div></div></section>
  <section class="section"><span class="no">03</span><div><h2>Capabilities</h2><div class="skill-grid"><div><h3>Interface</h3><p>React, Next.js, TypeScript, React Native, Tailwind</p></div><div><h3>Systems</h3><p>Web Components, Node.js, REST, WebSockets, PostgreSQL, AWS</p></div><div><h3>ML</h3><p>PyTorch, LoRA/PEFT, VLMs, HuggingFace, RAG</p></div><div><h3>Focus</h3><p>Design systems, accessibility, performance, on-device inference</p></div></div></div></section>
  <section class="section"><span class="no">04</span><div><h2>Education</h2><div class="edu"><strong>MSc Artificial Intelligence · University of Edinburgh</strong><span class="muted">Incoming · Sep 2026—27</span></div><div class="edu"><strong>B.Tech Computer Science · IIT Jodhpur</strong><span class="muted">May 2023 · 8.0/10</span></div></div></section>
</main>`;

const projectForward = `
<style>${sharedStyles}
  .resume{padding:12px 0 40px}.top{display:flex;justify-content:space-between;gap:32px;align-items:flex-start;padding:22px 0 30px}.top h1{font-size:clamp(48px,9vw,76px);font-weight:400;line-height:.92;letter-spacing:-.05em}.top-copy{max-width:390px;padding-top:8px}.top-copy>p{font-size:17px}.contact{margin-top:15px;font-size:12px}.label{display:flex;align-items:center;gap:12px;margin:10px 0 14px}.label:after{content:'';height:1px;background:rgba(0,0,0,.18);flex:1}.featured{display:grid;grid-template-columns:1.3fr .7fr .7fr;grid-template-rows:auto auto;gap:10px}.card{border:1px solid rgba(0,0,0,.14);border-radius:10px;padding:20px;min-height:160px;background:rgba(255,255,255,.18)}.card:first-child{grid-row:span 2;min-height:330px;display:flex;flex-direction:column;justify-content:space-between;background:#111;color:#fdf5e2}.card h3{font-family:Canela,Georgia,serif;font-size:24px;font-weight:400;margin-bottom:8px}.card:first-child h3{font-size:40px}.metric{font-size:36px;line-height:1;font-weight:700;letter-spacing:-.04em;margin-top:28px}.card-links{margin-top:12px}.lower{display:grid;grid-template-columns:1.2fr .8fr;gap:34px;margin-top:34px}.lower section{border-top:1px solid rgba(0,0,0,.18);padding-top:18px}.role+.role{margin-top:22px}.role-head{display:flex;justify-content:space-between;gap:16px}.role h3{font-size:15px}.date{font-size:11px;color:#6b7280;white-space:nowrap}.side-block+.side-block{margin-top:26px}.side-block h2{margin-bottom:10px}.pills{display:flex;flex-wrap:wrap;gap:6px}.pills span{padding:4px 8px;background:#f5edd8;border-radius:5px;font-size:11px}@media(max-width:700px){.top{display:block}.top-copy{margin-top:22px}.featured{grid-template-columns:1fr 1fr}.card:first-child{grid-column:1/-1;grid-row:auto;min-height:240px}.lower{grid-template-columns:1fr}.role-head{display:block}.date{display:block;margin:3px 0 8px}}@media(max-width:430px){.featured{grid-template-columns:1fr}.card:first-child{grid-column:auto}.card{min-height:0}}
</style>
<main class="resume">
  <header class="top"><div><p class="caps muted">Builder’s résumé / 2026</p><h1 class="serif">Tarun<br>Tomar</h1></div><div class="top-copy"><p>I make infrastructure for designers and engineers at Adobe—and small, fast AI products for everyone else.</p><div class="contact muted"><a href="mailto:tomartarun2001@gmail.com">email</a><a href="https://www.tarat.space">portfolio</a><a href="https://github.com/TarunTomar122">github</a><a href="https://x.com/tarat_211">twitter</a></div></div></header>
  <div class="label"><h2 class="caps">Things that shipped</h2></div><section class="featured">
    <article class="card"><div><p class="caps">On-device AI</p><h3>Lumi</h3><p>A natural-language, offline-first Android task manager powered by a fine-tuned 350M-parameter model.</p><p class="card-links"><a href="https://www.tarat.space/projects/lumi">Case study ↗</a></p></div><div><p class="metric">&lt;100ms</p><p>inference · 400+ users · paid conversions</p></div></article>
    <article class="card"><h3>Vision NanoChat</h3><p>64× visual-token compression with BLIP-2 and a custom 1.5M projection layer.</p><p class="card-links"><a href="https://www.tarat.space/projects/deepseek-nanochat-1">See experiment ↗</a></p></article>
    <article class="card"><h3>YourTrace</h3><p>AI/tech daily briefing. Product Hunt #7 and 200+ mobile downloads.</p><p class="card-links"><a href="https://yourtrace.online">Visit ↗</a></p></article>
    <article class="card"><h3>StocksBrew</h3><p>AI-curated stock news before market open, with recurring subscribers.</p><p class="card-links"><a href="https://stocksbrew.online">Visit ↗</a></p></article>
    <article class="card"><h3>Garden RAG</h3><p>Semantic search across my writing, projects, and work—entirely client-side.</p><p class="card-links"><a href="https://www.tarat.space/tarat-ai">Ask it ↗</a></p></article>
  </section>
  <div class="lower"><section><h2 class="caps muted">Work</h2><article class="role"><div class="role-head"><h3>Adobe · Design Engineer (SDE II)</h3><span class="date">Jun 2023 — Present</span></div><ul><li>Led Spectrum Web Components’ architectural migration to Spectrum 2.0 across Firefly, Illustrator Web, Adobe.com, and thousands of engineers.</li><li>Built App Frame for accessible, consistent cross-platform rendering.</li><li>Created tooling to track component adoption across Adobe; promoted January 2025.</li></ul></article><article class="role"><div class="role-head"><h3>Adobe · Emerging Tech Intern</h3><span class="date">May — Jul 2022</span></div><p>Built a multimodal GenAI assistant for Adobe Express with template matching, context-aware canvas editing, and asset generation.</p></article></section>
    <aside><div class="side-block"><h2 class="caps muted">Education</h2><p><strong>University of Edinburgh</strong><br>MSc Artificial Intelligence, incoming Sep 2026</p><p style="margin-top:10px"><strong>IIT Jodhpur</strong><br>B.Tech Computer Science, 8.0/10</p></div><div class="side-block"><h2 class="caps muted">Working set</h2><div class="pills"><span>TypeScript</span><span>React</span><span>Next.js</span><span>Web Components</span><span>Design systems</span><span>Accessibility</span><span>Python</span><span>PyTorch</span><span>VLMs</span><span>LoRA</span><span>On-device AI</span><span>RAG</span></div></div><div class="side-block"><h2 class="caps muted">Next</h2><p>Relocating to Edinburgh in September 2026. Focused on embodied AI, VLA systems, and efficient on-device inference.</p></div></aside>
  </div>
</main>`;

export const RESUME_VARIANTS: readonly ResumeVariant[] = [
  { name: "editorial", html: editorial },
  { name: "sidebar", html: sidebar },
  { name: "swiss", html: swiss },
  { name: "project-forward", html: projectForward },
];

export function pickResumeVariant(): ResumeVariant {
  return RESUME_VARIANTS[Math.floor(Math.random() * RESUME_VARIANTS.length)];
}
